apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: pacman-ingress
  namespace: pacmangit
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: pacman.dev-adv.net
    http:
      paths:
      - backend:
          serviceName: pacmangit
          servicePort: 8080
